remote_theme: kmgallahan/just-the-docs
title: Style as Code
description: Style as Code helps develops produce code with a consistent style.

#Theme settings:
search_enabled: true
aux_links:
  "GitHub":
    - "//github.com/kmgallahan/Style-as-Code"
heading_anchors: true
color_scheme: "dark"
github_url: "kmgallahan.github.io/Style-as-Code"
