remote_theme: kmgallahan/just-the-docs
title: Style as Code
description: Style as Code helps developers produce code with a consistent style.

#Theme settings:
search_enabled: true
ga_tracking: UA-157517290-1
heading_anchors: true
color_scheme: "dark"
github_url: "https://github.com/kmgallahan/Style-as-Code"
github_docs: "https://github.com/kmgallahan/Style-as-Code/tree/master/docs"
